app/Http/routes.php
<?php

Route::auth();
Route::get('/', 'HomeController@index');

//cookie tahun
Route::resource('tahun', 'Web\Admin\TahunAjaranController');
Route::resource('home', 'HomeController');
Route::resource('admin/beranda', 'Web\Admin\BerandaController');

// jurusan
Route::resource('admin/jurusan', 'Web\Admin\JurusanController');
Route::resource('admin/kelas', 'Web\Admin\KelasController');

//siswa
Route::resource('admin/siswa', 'Web\Admin\SiswaController');
Route::resource('admin/siswa/hapus', 'Web\Admin\SiswaController@hapus');
Route::resource('admin/siswa/balikin', 'Web\Admin\SiswaController@balikin');
Route::resource('admin/siswawali', 'Web\Admin\SiswaWaliController');
// Route::post('admin/siswa/upload', 'Admin\SiswaController@postSiswa'); //upload data lewat excel

//guru
Route::resource('admin/guru', 'Web\Admin\GuruController');
Route::resource('admin/guru/hapus', 'Web\Admin\GuruController@hapus');
Route::resource('admin/guru/balikin', 'Web\Admin\GuruController@balikin');
Route::resource('admin/walikelas', 'Web\Admin\WaliKelasController');
Route::resource('admin/gurupiket', 'Web\Admin\GuruPiketController');

//kotak sampah
Route::resource('admin/sampah', 'Web\Admin\KotakSampahController');

//mata pelajaran
Route::resource('admin/mapel/na', 'Web\Admin\MapelNaController');
Route::resource('admin/mapel/pro', 'Web\Admin\MapelProController');
Route::resource('admin/mapel/pemapel', 'Web\Admin\PembagianMapelController');

//jadwal pelajaran
Route::resource('admin/jadwal/jadwal', 'Web\Admin\JadwalController');
Route::get('admin/jadwal/pemapel/{id}','Web\Admin\JadwalController@pemapel');
Route::resource('admin/jadwal/guru', 'Web\Admin\JadwalController@guru');
Route::resource('admin/jadwal/guru/hapus', 'Web\Admin\JadwalController@hapus');

//akun
Route::resource('admin/akun/admin', 'Web\Admin\AkunController');
Route::resource('admin/akun/guru', 'Web\Admin\AkunGuruController');
Route::resource('admin/akun/siswa', 'Web\Admin\AkunSiswaController');

//Pegaturan
Route::resource('admin/pengaturan', 'Web\Admin\PengaturanController');
Route::resource('admin/agama', 'Web\Admin\AgamaController');
Route::resource('admin/jam', 'Web\Admin\JamController');
Route::resource('admin/jabatan', 'Web\Admin\JabatanController');
Route::resource('admin/pekerjaan', 'Web\Admin\PekerjaanController');
Route::resource('admin/pendidikan', 'Web\Admin\PendidikanController');
Route::resource('admin/penghasilan', 'Web\Admin\PenghasilanController');
Route::resource('admin/status', 'Web\Admin\StatusController');
Route::post('admin/ta', 'Web\Admin\TahunAjaranController@tambah');
// Route::resource('admin/jumlah', 'Admin\JumlahSoalController');

//Absensi
Route::resource('admin/absensi', 'Web\Admin\AbsensiController');
Route::resource('admin/absensi/absensi/{id}', 'Web\Admin\AbsensiController@absensi');
Route::resource('admin/absensi/data', 'Web\Admin\AbsensiController@data');

//ujian
// Route::resource('admin/ujian/midsega', 'Admin\UjianMidsegaController');
// Route::resource('admin/ujian/midsege', 'Admin\UjianMidsegeController');
// Route::resource('admin/ujian/ujisega', 'Admin\UjianSegaController');
// Route::resource('admin/ujian/ujisege', 'Admin\UjianSegeController');

// Route::get('admin/ujian/pemapel/{id}','Admin\UjianMidsegaController@pemapel');
// Route::get('admin/ujian/mapel/{id}','Admin\UjianMidsegaController@mapel');
// Route::get('admin/ujian/jadwal/{id}/{mapel}','Admin\UjianMidsegaController@jadwal');

// Route::resource('admin/ujian/soal', 'Admin\SoalController');
// Route::resource('admin/ujian/nilai', 'Admin\NilaiController');
// Route::post('admin/ujian/nilai/cetak', 'Admin\NilaiController@getPDF');
// Route::get('admin/ujian/matapel/{id}','Admin\NilaiController@jadwal');

//NaikKelas
// Route::resource('admin/naikkelas', 'Admin\NaikKelasController');




//      GGGGGGGGGGGG   UUU     UUU   RRRRRRR       UUU     UUU
//      GGGGGGGGGGGG   UUU     UUU   RRRRRRRR      UUU     UUU
//      GGG      GGG   UUU     UUU   RRR   RRR     UUU     UUU
//      GGG      GGG   UUU     UUU   RRR   RRR     UUU     UUU
//      GGG            UUU     UUU   RRR RRRR      UUU     UUU
//      GGG   GGGGGG   UUU     UUU   RRRRRRR       UUU     UUU
//      GGG   GGGGGG   UUU     UUU   RRRRRR        UUU     UUU
//      GGG      GGG   UUU     UUU   RRR  RRR      UUU     UUU
//      GGG      GGG   UUU     UUU   RRR   RRR     UUU     UUU
//      GGGGGGGGGGGG   UUUUUUUUUUU   RRR    RRR    UUUUUUUUUUU
//      GGGGGGGGGGGG   UUUUUUUUUUU   RRR     RRR   UUUUUUUUUUU



//profil
Route::resource('guru/beranda', 'Web\Guru\BerandaController');
Route::resource('guru/profil', 'Web\Guru\ProfilController');

//siswa
Route::resource('guru/siswa', 'Web\Guru\SiswaController');

//jadwal
Route::resource('guru/jadwal', 'Web\Guru\JadwalController');

//wali
Route::resource('guru/walikelas/siswa', 'Web\Guru\WaliSiswaController');

//pengaturan
// Route::resource('guru/pengaturan', 'Guru\PengaturanController');
// Route::resource('guru/akun', 'Guru\AkunController');

//ujian
// Route::resource('guru/ujian/soal', 'Guru\SoalController');
// Route::resource('guru/ujian/nilai', 'Guru\NilaiController');
// Route::post('guru/ujian/nilai/cetak', 'Guru\NilaiController@getPDF');
// Route::get('guru/ujian/matapel/{id}','Guru\NilaiController@jadwal');



//      SSSSSSSSSSSS  IIII   SSSSSSSSSSSS  WWW           WWW   AAAAAAAAAAAA
//      SSSSSSSSSSSS  IIII   SSSSSSSSSSSS  WWW           WWW   AAAAAAAAAAAA
//      SSS      SSS  IIII   SSS      SSS  WWW           WWW   AAA      AAA
//      SSS           IIII   SSS           WWW           WWW   AAA      AAA
//      SSSSSSSSSSSS  IIII   SSSSSSSSSSSS  WWW    WWW    WWW   AAAAAAAAAAAA
//      SSSSSSSSSSSS  IIII   SSSSSSSSSSSS  WWW   WWWWW   WWW   AAAAAAAAAAAA
//               SSS  IIII            SSS  WWW  WWWWWWW  WWW   AAA      AAA
//      SSS      SSS  IIII   SSS      SSS  WWW WWW   WWW WWW   AAA      AAA
//      SSSSSSSSSSSS  IIII   SSSSSSSSSSSS  WWWWWW     WWWWWW   AAA      AAA
//      SSSSSSSSSSSS  IIII   SSSSSSSSSSSS  WWWWWW     WWWWWW   AAA      AAA


//profil
// Route::resource('siswa/profil', 'Siswa\ProfilController');
// Route::resource('siswa/profil/wali', 'Siswa\WaliController');

//pengaturan
// Route::resource('siswa/pengaturan', 'Siswa\PengaturanController');
// Route::resource('siswa/akun', 'Siswa\AkunController');

//jadwal
// Route::resource('siswa/jadwal', 'Siswa\JadwalController');

//nilai
// Route::resource('siswa/nilai/midsega', 'Siswa\NilaiMidsegaController');
// Route::resource('siswa/nilai/midsege', 'Siswa\NilaiMidsegeController');
// Route::resource('siswa/nilai/ujisega', 'Siswa\NilaiSegaController');
// Route::resource('siswa/nilai/ujisege', 'Siswa\NilaiSegeController');

//ujian
// Route::resource('siswa/ujian/midsega', 'Siswa\UjianMidsegaController');
// Route::resource('siswa/ujian/midsege', 'Siswa\UjianMidsegeController');
// Route::resource('siswa/ujian/ujisega', 'Siswa\UjianSegaController');
// Route::resource('siswa/ujian/ujisege', 'Siswa\UjianSegeController');

// Route::get('siswa/ujian/midsega/ujian/{id}', 'Siswa\UjianMidsegaController@ujian');
// Route::get('siswa/ujian/midsege/ujian/{id}', 'Siswa\UjianMidsegeController@ujian');
// Route::get('siswa/ujian/ujisega/ujian/{id}', 'Siswa\UjianSegaController@ujian');
// Route::get('siswa/ujian/ujisege/ujian/{id}', 'Siswa\UjianSegeController@ujian');

// Route::resource('siswa/ujian/exam/midsega', 'Siswa\ExamMidsegaController');
// Route::resource('siswa/ujian/exam/midsege', 'Siswa\ExamMidsegeController');
// Route::resource('siswa/ujian/exam/ujisega', 'Siswa\ExamSegaController');
// Route::resource('siswa/ujian/exam/ujisege', 'Siswa\ExamSegeController');

// Route::get('siswa/ujian/exam/jawaban/{id}/{jawab}','Siswa\ExamMidsegaController@jawab');

app/Http/Controllers/Web/Admin/SiswaController.php
<?php

namespace App\Http\Controllers\Web\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Http\Requests\CreateSiswaRequest;
use App\Http\Requests\SiswaRequest;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use File;

use App\Siswa;
use App\SiswaMeta;
use App\SiswaWali;
use App\User;
use App\Kelas;
use App\Agama;
use App\Pekerjaan;
use App\Pendidikan;
use App\Penghasilan;
use App\TahunAjaran;

use Alert;
use DB;

class SiswaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:admin');
    }

    public function index(Request $request)
    {
        $tahun_ajaran = $request->cookie('tahun_ajaran');

        $q = $request->get('q');
        $kelas_id = $request->get('kelas_id');
        $page = $request->get('page');

        $no = 1;

        if($page>1){
            $no = $page * 5 - 4;
        }else{
            $no=1;
        }

        $kelas = Kelas::lists('kode_kelas', 'id');

        $siswa = Siswa::where('nama', 'LIKE', '%'.$q.'%')
            ->where('kelas_id', 'LIKE', '%'.$kelas_id.'%')
            ->where('tahun_ajaran', $tahun_ajaran)
            ->where('hapus', '0')
            ->orderBy('kelas_id','asc')
            ->orderBy('nama','asc')
            ->paginate(9);

        return view('admin.siswa.siswa', compact('siswa', 'no' ,'q', 'kelas'));
    }

    public function create(Request $request)
    {
        $agama = Agama::lists('agama', 'id');
        $kelas = Kelas::lists('kode_kelas', 'id');
        $pekerjaan = Pekerjaan::lists('pekerjaan', 'pekerjaan');
        $penghasilan = Penghasilan::lists('penghasilan', 'penghasilan');
        $pendidikan = Pendidikan::lists('pendidikan', 'pendidikan');

        return view('admin.siswa.tambah_siswa', compact('agama','kelas','pendidikan','pekerjaan','penghasilan'));
    }

    public function store(CreateSiswaRequest $request)
    {
        // SIMPAN DATA SISWA
        $dataSiswa = $request->only('agama_id','kelas_id','no_induk','nama','tahun_ajaran','hapus');
        
        Siswa::create($dataSiswa);

        // SIMPAN DATA SISWA META
        $dataSiswaMeta = $request->only('no_induk','nisn','jk','tempat_lahir','tanggal_lahir','alamat',
        'rt','rw','desa','kecamatan','kabupaten','provinsi','kode_pos','telp');

        if ($request->hasFile('photo')) {
            $dataSiswaMeta['photo'] = $this->savePhoto($request->file('photo'));
        } else {
            if($request->jk == 'laki-laki'){
              $dataSiswaMeta['photo'] = 'avatar1.png';
            } else {
              $dataSiswaMeta['photo'] = 'avatar3.png';
            }
        }

        SiswaMeta::create($dataSiswaMeta);

        // SIMPAN DATA SISWA WALI
        $dataSiswaWali = $request->only('no_induk',
            'ayah_nama','ayah_tl','ayah_pekerjaan','ayah_penghasilan','ayah_pendidikan','ayah_telp',
            'ibu_nama','ibu_tl','ibu_pekerjaan','ibu_penghasilan','ibu_pendidikan','ibu_telp',
            'wali_nama','wali_tl','wali_pekerjaan','wali_penghasilan','wali_pendidikan','wali_telp');

        SiswaWali::create($dataSiswaWali);

        // SIMPAN DATA USER
        User::create([
            'no_induk'  => $request->no_induk,
            'email'     => $request->no_induk.'@smkpelitapesawaran.sch.id',
            'username'  => $request->no_induk,
            'password'  => bcrypt('smkpelita'),
            'api_token' => bcrypt($request->no_induk.'@smkpelitapesawaran.sch.id'),
            'role'      => 'siswa'
        ]);

        Alert::success('Success Message', 'Siswa dengan nama '.$request->get('nama').' telah ditambahkan.');
        // Session::flash('success', 'Siswa dengan nama '.$request->get('nama').' telah ditambahkan.');
        return redirect()->route('admin.siswa.index');
    }


    public function show($id)
    {
        //
    }


    public function edit($id)
    {
        $agama = Agama::lists('agama', 'id');
        $kelas = Kelas::lists('kode_kelas', 'id');
  
        $siswa      = Siswa::findOrFail($id); 
  
        return view('admin.siswa.edit_siswa', compact('siswa','agama','kelas'));
    }

    public function update(SiswaRequest $request, $id)
    {
        // SIMPAN DATA SISWA
        $siswa = Siswa::findOrFail($id);

        $dataSiswa = $request->only('agama_id','kelas_id','no_induk','nama','tahun_ajaran','hapus');
        
        $siswa->update($dataSiswa);

        // SIMPAN DATA SISWA META
        $dataSiswaMeta = $request->only('nisn','jk','tempat_lahir','tanggal_lahir','alamat',
        'rt','rw','desa','kecamatan','kabupaten','provinsi','kode_pos','telp');

        if ($request->hasFile('photo')) {
            $dataSiswaMeta['photo'] = $this->savePhoto($request->file('photo'));
            if (($siswa->siswa_meta->photo == 'avatar1.png')||($siswa->siswa_meta->photo == 'avatar3.png')) {

            } else {
              $this->deletePhoto($siswa->photo);
            }
        } else {
            if($siswa->photo !== ('avatar1.png')||('avatar3.png')) {
              $dataSiswaMeta['photo'] = $siswa->siswa_meta->photo;
            } elseif ($request->jk == 'laki-laki') {
              $dataSiswaMeta['photo'] = 'avatar1.png';
            } else {
              $dataSiswaMeta['photo'] = 'avatar3.png';
            }
        }

        $siswa_meta = SiswaMeta::findOrFail($id);

        $siswa_meta->update($dataSiswaMeta);

        Alert::success('Success Message', 'Siswa dengan nama '.$request->get('nama').' telah diubah.');
        // Session::flash('info', 'Siswa dengan nama '.$request->get('nama').' telah diubah.');
        return redirect()->route('admin.siswa.index');
    }

    // HAPUS DATA SISWA SEMENTARA
    public function hapus($id)
    {
        $hapus = Siswa::findOrFail($id);
  
        DB::update('update siswas set hapus = "1" where id = '.$id);
  
        return redirect()->route('admin.siswa.index');
    }

    // KEMBALIKAN DATA SISWA SEMENTARA
    public function balikin($id)
    {
        $hapus = Siswa::findOrFail($id);

        DB::update('update siswas set hapus = "0" where id = '.$id);

        return redirect()->route('admin.sampah.index');
    }

    public function destroy($id)
    {
        $hapus = Siswa::findOrFail($id);
        // Session::flash('error', 'Siswa dengan nama '.$hapus->nama.' telah dihapus permanen.');
  
        $siswa = DB::table('siswas')->where('id',$id);

        //delete siswa
        $siswa      = Siswa::find($id);
        $siswa_wali = SiswaWali::find($id);
        $siswa_meta = SiswaMeta::find($id);
  
        if ($siswa->siswa_meta->photo !== ('avatar1.png')&&('avatar3.png')) $this->deletePhoto($siswa->siswa_meta->photo);
  
        //delete siswa
        $siswa->delete();

        //delete siswa meta
        $siswa_meta->delete();
  
        //delete wali
        $siswa_wali->delete();
  
        //delete user
        $user = User::where('no_induk',$siswa->no_induk);
        $user->delete();
  
        return redirect()->route('admin.siswa.index');
    }

    protected function savePhoto(UploadedFile $photo)
    {
      $fileName = str_random(40) . '.' . $photo->guessClientExtension();
      $destinationPath = 'img/siswa';
      $photo->move($destinationPath, $fileName);
      return $fileName;
    }

    public function deletePhoto($filename)
    {
      $path = 'img/siswa/'.$filename;
      return File::delete($path);
    }
}

app/Http/Controllers/Web/Guru/SiswaController.php
<?php

namespace App\Http\Controllers\Web\Guru;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Kelas;
use App\Siswa;

class SiswaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:guru');
    }

    public function index(Request $request)
    {
        $tahun_ajaran = $request->cookie('tahun_ajaran');

        $q = $request->get('q');
        $kelas_id = $request->get('kelas_id');
        $page = $request->get('page');

        $no = 1;

        if($page>1){
            $no = $page * 5 - 4;
        }else{
            $no=1;
        }

        $kelas = Kelas::lists('kode_kelas', 'id');

        $siswa = Siswa::where('nama', 'LIKE', '%'.$q.'%')
            ->where('kelas_id', 'LIKE', '%'.$kelas_id.'%')
            ->where('tahun_ajaran', $tahun_ajaran)
            ->where('hapus', '0')
            ->orderBy('kelas_id','asc')
            ->orderBy('nama','asc')
            ->paginate(9);

        return view('guru.siswa.siswa', compact('siswa', 'no' ,'q', 'kelas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/siswa/_profil.blade.php
<div class="box box-widget widget-user">
    {{--  HEADER  --}}
    <div class="widget-user-header bg-aqua-active">
        <h3 class="widget-user-username">{{ $item->nama }}</h3>
        <h5 class="widget-user-desc">{{ $item->kelas->kode_kelas }}</h5>
    </div>

    {{--  IMAGE PROFIL  --}}
    <div class="widget-user-image">
        <img class="img-circle" src="{{ url('img/siswa/' . $item->siswa_meta->photo) }}" alt="User Avatar">
    </div>

    {{--  DATA  --}}
    <div class="box-footer">
        <div class="row">

            {{--  DATA WALI  --}}
            <div class="col-sm-4 border-right">
                <div class="description-block">
                    <button class="btn btn-success" data-toggle="modal" data-target="#ortu-{{ $item->id }}">Wali</button>

                    <div class="modal modal-success fade" id="ortu-{{ $item->id }}" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                    <h4 class="modal-title" id="{{ $item->id }}">
                                        <img class="img-circle" src="{{ url('img/siswa/' . $item->siswa_meta->photo) }}" width="150" height="150" class="img-circle" alt="User Image"><br>
                                        Orang Tua / Wali<br>
                                        {{ $item->nama }}
                                    </h4>
                                </div>

                                <div class="modal-body">
                                    <div class="row">
                                        <div class="col-sm-3">
                                            <strong>Label</strong><br>
                                            Nama<br>
                                            Tahun Lahir<br>
                                            Pendidikan<br>
                                            Pekerjaan<br>
                                            Penghasilan<br>
                                            Telp / HP
                                        </div>
                                        <div class="col-sm-3">
                                            <strong>Ayah</strong><br>
                                            {{ $item->siswa_wali->ayah_nama }}<br>
                                            {{ $item->siswa_wali->ayah_tl }}<br>
                                            {{ $item->siswa_wali->ayah_pendidikan }}<br>
                                            {{ $item->siswa_wali->ayah_pekerjaan }}<br>
                                            {{ $item->siswa_wali->ayah_penghasilan }}<br>
                                            {{ $item->siswa_wali->ayah_telp }}
                                        </div>
                                        <div class="col-sm-3">
                                            <strong>Ibu</strong><br>
                                            {{ $item->siswa_wali->ibu_nama }}<br>
                                            {{ $item->siswa_wali->ibu_tl }}<br>
                                            {{ $item->siswa_wali->ibu_pendidikan }}<br>
                                            {{ $item->siswa_wali->ibu_pekerjaan }}<br>
                                            {{ $item->siswa_wali->ibu_penghasilan }}<br>
                                            {{ $item->siswa_wali->ibu_telp }}
                                        </div>
                                        <div class="col-sm-3">
                                            <strong>Wali</strong><br>
                                            {{ $item->siswa_wali->wali_nama }}<br>
                                            {{ $item->siswa_wali->wali_tl }}<br>
                                            {{ $item->siswa_wali->wali_pendidikan }}<br>
                                            {{ $item->siswa_wali->wali_pekerjaan }}<br>
                                            {{ $item->siswa_wali->wali_penghasilan }}<br>
                                            {{ $item->siswa_wali->wali_telp }}
                                        </div>
                                    </div>
                                </div>

                                <div class="modal-footer">
                                    <button onclick="window.location.href='{{ route('admin.siswawali.edit', $item->id) }}'" class="btn btn-default">Ubah</button>
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Keluar</button>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

            {{--  DATA SISWA  --}}
            <div class="col-sm-4 border-right">
                <div class="description-block">
                    <button class="btn btn-primary" data-toggle="modal" data-target="#detail-{{ $item->id }}">Detail</button>

                    <div class="modal modal-primary fade" id="detail-{{ $item->id }}" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                    <h4 class="modal-title" id="{{ $item->id }}">
                                        <img class="img-circle" src="{{ url('img/siswa/' . $item->siswa_meta->photo) }}" width="150" height="150" class="img-circle" alt="User Image"><br>
                                        {{ $item->nama }}<br>
                                        {{ $item->kelas->kode_kelas }}
                                    </h4>
                                </div>

                                <div class="modal-body">
                                    <div class="row">
                                        <div class="col-sm-3">
                                            <strong>Agama<br>
                                            NIS<br>
                                            Tempat lahir</strong>
                                        </div>
                                        <div class="col-sm-3">
                                            {{ $item->agama->agama }}<br>
                                            {{ $item->no_induk }}<br>
                                            {{ $item->siswa_meta->tempat_lahir }}
                                        </div>
                                        <div class="col-sm-3">
                                            <strong>Jenis Kelamin<br>
                                            NISN<br>
                                            Tanggal Lahir</strong>
                                        </div>
                                        <div class="col-sm-3">
                                            {{ $item->siswa_meta->jk }}<br>
                                            {{ $item->siswa_meta->nisn }}<br>
                                            {{ $item->siswa_meta->tanggal_lahir }}
                                        </div>
                                    </div>
                                    <div class="row">
                                        <br>Alamat : {{ $item->siswa_meta->alamat }}, RT / RW : {{ $item->siswa_meta->rt }} / {{ $item->siswa_meta->rw }}<br><br>
                                    </div>
                                    <div class="row">
                                        <div class="col-sm-3">
                                            <strong>Dusun / Desa<br>
                                            Kecamatan</strong>
                                        </div>
                                        <div class="col-sm-3">
                                            {{ $item->siswa_meta->desa }}<br>
                                            {{ $item->siswa_meta->kecamatan }}
                                        </div>
                                        <div class="col-sm-3">
                                            <strong>Kabupaten / Kota<br>
                                            Provinsi</strong>
                                        </div>
                                        <div class="col-sm-3">
                                            {{ $item->siswa_meta->kabupaten }}<br>
                                            {{ $item->siswa_meta->provinsi }}
                                        </div>
                                    </div>
                                    <div class="row">
                                        <br>Kode POS : {{ $item->siswa_meta->kode_pos }} <=> Telp : {{ $item->siswa_meta->telp }}
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button onclick="window.location.href='{{ route('admin.siswa.edit', $item->id) }}'" class="btn btn-default">Ubah</button>
                                    <button type="button" class="btn btn-danger" data-dismiss="modal">Keluar</button>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

            {{--  HAPUS SISWA  --}}
            <div class="col-sm-4">
                <div class="description-block">
                    {{ Form::open(['url' => ['admin/siswa/hapus' ,$item->id] ,'method' => 'PUT']) }}
                      {{ Form::submit('Hapus', ['class' => 'btn btn-danger js-submit-confirm']) }}
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/admin/siswa/edit_siswa.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Siswa
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12" align="right">
                <a href="{{ url('/admin/siswa') }}" class="btn btn-primary"><span class="fa fa-eye"></span> Data Siswa</a>
                <br><br>
            </div>
            <div class="col-md-12">
                {!! Form::model($siswa, ['route' => ['admin.siswa.update', $siswa],'method' =>'patch','class'=>'form-horizontal','files'=>true])!!}
                    @include('form._admin_edit_siswa', ['model' => $siswa])
                {!! Form::close() !!}
            </div>
        </div>
    </section>
@endsection

resources/views/admin/siswa/tambah_siswa.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Siswa
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12" align="right">
                <a href="{{ url('/admin/siswa') }}" class="btn btn-primary"><span class="fa fa-eye"></span> Data Siswa</a>
                <br><br>
            </div>

            <div class="col-md-12">
                {!! Form::open(['route' => 'admin.siswa.store', 'class'=>'form-horizontal','files'=>true])!!}
                    @include('form._admin_siswa')
                {!! Form::close() !!}
            </div>
        </div>
    </section>
@endsection