app/Http/routes.php
<?php

Route::auth();
Route::get('/', 'HomeController@index');

//cookie tahun
Route::resource('tahun', 'Web\Admin\TahunAjaranController');
Route::resource('home', 'HomeController');
Route::resource('admin/beranda', 'Web\Admin\BerandaController');

// jurusan
Route::resource('admin/jurusan', 'Web\Admin\JurusanController');
Route::resource('admin/kelas', 'Web\Admin\KelasController');

//siswa
Route::resource('admin/siswa', 'Web\Admin\SiswaController');
Route::resource('admin/siswa/hapus', 'Web\Admin\SiswaController@hapus');
Route::resource('admin/siswa/balikin', 'Web\Admin\SiswaController@balikin');
Route::resource('admin/siswawali', 'Web\Admin\SiswaWaliController');
// Route::post('admin/siswa/upload', 'Admin\SiswaController@postSiswa'); //upload data lewat excel

//guru
Route::resource('admin/guru', 'Web\Admin\GuruController');
Route::resource('admin/guru/hapus', 'Web\Admin\GuruController@hapus');
Route::resource('admin/guru/balikin', 'Web\Admin\GuruController@balikin');
Route::resource('admin/walikelas', 'Web\Admin\WaliKelasController');
Route::resource('admin/gurupiket', 'Web\Admin\GuruPiketController');

//kotak sampah
Route::resource('admin/sampah', 'Web\Admin\KotakSampahController');

//mata pelajaran
Route::resource('admin/mapel/na', 'Web\Admin\MapelNaController');
Route::resource('admin/mapel/pro', 'Web\Admin\MapelProController');
Route::resource('admin/mapel/pemapel', 'Web\Admin\PembagianMapelController');

//jadwal pelajaran
Route::resource('admin/jadwal/jadwal', 'Web\Admin\JadwalController');
Route::get('admin/jadwal/pemapel/{id}','Web\Admin\JadwalController@pemapel');
Route::resource('admin/jadwal/guru', 'Web\Admin\JadwalController@guru');
Route::resource('admin/jadwal/guru/hapus', 'Web\Admin\JadwalController@hapus');

//akun
Route::resource('admin/akun/admin', 'Web\Admin\AkunController');
Route::resource('admin/akun/guru', 'Web\Admin\AkunGuruController');
Route::resource('admin/akun/siswa', 'Web\Admin\AkunSiswaController');

//Pegaturan
Route::resource('admin/pengaturan', 'Web\Admin\PengaturanController');
Route::resource('admin/agama', 'Web\Admin\AgamaController');
Route::resource('admin/jam', 'Web\Admin\JamController');
Route::resource('admin/jabatan', 'Web\Admin\JabatanController');
Route::resource('admin/pekerjaan', 'Web\Admin\PekerjaanController');
Route::resource('admin/pendidikan', 'Web\Admin\PendidikanController');
Route::resource('admin/penghasilan', 'Web\Admin\PenghasilanController');
Route::resource('admin/status', 'Web\Admin\StatusController');
Route::post('admin/ta', 'Web\Admin\TahunAjaranController@tambah');
// Route::resource('admin/jumlah', 'Admin\JumlahSoalController');

//Absensi
Route::resource('admin/absensi', 'Web\Admin\AbsensiController');
Route::resource('admin/absensi/absensi/{id}', 'Web\Admin\AbsensiController@absensi');
Route::resource('admin/absensi/data', 'Web\Admin\AbsensiController@data');

//ujian
// Route::resource('admin/ujian/midsega', 'Admin\UjianMidsegaController');
// Route::resource('admin/ujian/midsege', 'Admin\UjianMidsegeController');
// Route::resource('admin/ujian/ujisega', 'Admin\UjianSegaController');
// Route::resource('admin/ujian/ujisege', 'Admin\UjianSegeController');

// Route::get('admin/ujian/pemapel/{id}','Admin\UjianMidsegaController@pemapel');
// Route::get('admin/ujian/mapel/{id}','Admin\UjianMidsegaController@mapel');
// Route::get('admin/ujian/jadwal/{id}/{mapel}','Admin\UjianMidsegaController@jadwal');

// Route::resource('admin/ujian/soal', 'Admin\SoalController');
// Route::resource('admin/ujian/nilai', 'Admin\NilaiController');
// Route::post('admin/ujian/nilai/cetak', 'Admin\NilaiController@getPDF');
// Route::get('admin/ujian/matapel/{id}','Admin\NilaiController@jadwal');

//NaikKelas
// Route::resource('admin/naikkelas', 'Admin\NaikKelasController');




//      GGGGGGGGGGGG   UUU     UUU   RRRRRRR       UUU     UUU
//      GGGGGGGGGGGG   UUU     UUU   RRRRRRRR      UUU     UUU
//      GGG      GGG   UUU     UUU   RRR   RRR     UUU     UUU
//      GGG      GGG   UUU     UUU   RRR   RRR     UUU     UUU
//      GGG            UUU     UUU   RRR RRRR      UUU     UUU
//      GGG   GGGGGG   UUU     UUU   RRRRRRR       UUU     UUU
//      GGG   GGGGGG   UUU     UUU   RRRRRR        UUU     UUU
//      GGG      GGG   UUU     UUU   RRR  RRR      UUU     UUU
//      GGG      GGG   UUU     UUU   RRR   RRR     UUU     UUU
//      GGGGGGGGGGGG   UUUUUUUUUUU   RRR    RRR    UUUUUUUUUUU
//      GGGGGGGGGGGG   UUUUUUUUUUU   RRR     RRR   UUUUUUUUUUU



//profil
Route::resource('guru/beranda', 'Web\Guru\BerandaController');
Route::resource('guru/profil', 'Web\Guru\ProfilController');

//siswa
Route::resource('guru/siswa', 'Web\Guru\SiswaController');

//jadwal
Route::resource('guru/jadwal', 'Web\Guru\JadwalController');

//wali
Route::resource('guru/walikelas/siswa', 'Web\Guru\WaliSiswaController');

//pengaturan
// Route::resource('guru/pengaturan', 'Guru\PengaturanController');
// Route::resource('guru/akun', 'Guru\AkunController');

//ujian
// Route::resource('guru/ujian/soal', 'Guru\SoalController');
// Route::resource('guru/ujian/nilai', 'Guru\NilaiController');
// Route::post('guru/ujian/nilai/cetak', 'Guru\NilaiController@getPDF');
// Route::get('guru/ujian/matapel/{id}','Guru\NilaiController@jadwal');



//      SSSSSSSSSSSS  IIII   SSSSSSSSSSSS  WWW           WWW   AAAAAAAAAAAA
//      SSSSSSSSSSSS  IIII   SSSSSSSSSSSS  WWW           WWW   AAAAAAAAAAAA
//      SSS      SSS  IIII   SSS      SSS  WWW           WWW   AAA      AAA
//      SSS           IIII   SSS           WWW           WWW   AAA      AAA
//      SSSSSSSSSSSS  IIII   SSSSSSSSSSSS  WWW    WWW    WWW   AAAAAAAAAAAA
//      SSSSSSSSSSSS  IIII   SSSSSSSSSSSS  WWW   WWWWW   WWW   AAAAAAAAAAAA
//               SSS  IIII            SSS  WWW  WWWWWWW  WWW   AAA      AAA
//      SSS      SSS  IIII   SSS      SSS  WWW WWW   WWW WWW   AAA      AAA
//      SSSSSSSSSSSS  IIII   SSSSSSSSSSSS  WWWWWW     WWWWWW   AAA      AAA
//      SSSSSSSSSSSS  IIII   SSSSSSSSSSSS  WWWWWW     WWWWWW   AAA      AAA


//profil
// Route::resource('siswa/profil', 'Siswa\ProfilController');
// Route::resource('siswa/profil/wali', 'Siswa\WaliController');

//pengaturan
// Route::resource('siswa/pengaturan', 'Siswa\PengaturanController');
// Route::resource('siswa/akun', 'Siswa\AkunController');

//jadwal
// Route::resource('siswa/jadwal', 'Siswa\JadwalController');

//nilai
// Route::resource('siswa/nilai/midsega', 'Siswa\NilaiMidsegaController');
// Route::resource('siswa/nilai/midsege', 'Siswa\NilaiMidsegeController');
// Route::resource('siswa/nilai/ujisega', 'Siswa\NilaiSegaController');
// Route::resource('siswa/nilai/ujisege', 'Siswa\NilaiSegeController');

//ujian
// Route::resource('siswa/ujian/midsega', 'Siswa\UjianMidsegaController');
// Route::resource('siswa/ujian/midsege', 'Siswa\UjianMidsegeController');
// Route::resource('siswa/ujian/ujisega', 'Siswa\UjianSegaController');
// Route::resource('siswa/ujian/ujisege', 'Siswa\UjianSegeController');

// Route::get('siswa/ujian/midsega/ujian/{id}', 'Siswa\UjianMidsegaController@ujian');
// Route::get('siswa/ujian/midsege/ujian/{id}', 'Siswa\UjianMidsegeController@ujian');
// Route::get('siswa/ujian/ujisega/ujian/{id}', 'Siswa\UjianSegaController@ujian');
// Route::get('siswa/ujian/ujisege/ujian/{id}', 'Siswa\UjianSegeController@ujian');

// Route::resource('siswa/ujian/exam/midsega', 'Siswa\ExamMidsegaController');
// Route::resource('siswa/ujian/exam/midsege', 'Siswa\ExamMidsegeController');
// Route::resource('siswa/ujian/exam/ujisega', 'Siswa\ExamSegaController');
// Route::resource('siswa/ujian/exam/ujisege', 'Siswa\ExamSegeController');

// Route::get('siswa/ujian/exam/jawaban/{id}/{jawab}','Siswa\ExamMidsegaController@jawab');

app/Http/Controllers/Web/Admin/AkunController.php
<?php

namespace App\Http\Controllers\Web\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Requests\AkunRequest;
use App\Http\Requests\AkunEditRequest;
use App\Http\Controllers\Controller;

use App\User;

class AkunController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:admin');
    }

    public function index(Request $request)
    {

        $q = $request->get('q');
        $page = $request->get('page');

        $no = 1;

        if($page>1){
            $no = $page * 5 - 4;
        }else{
            $no=1;
        }

        $akun = User::where('role','admin')
            // \->where('hapus', '0')
            ->orderBy('username','asc')
            ->paginate(10);

        return view('admin.akun.akun_admin', compact('akun', 'no'));
    }

    public function create()
    {
        //
    }

    public function store(AkunRequest $request)
    {
        $data = $request->only('username','no_induk');
        $data['role'] = 'admin';
        $data['password'] = bcrypt($request->get('password'));

        User::create($data);

        // Session::flash('success', 'Akun '.$request->get('username').' telah ditambahkan.');
        return redirect()->route('admin.akun.admin.index');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $akun = User::select('username','id')->findOrFail($id);

        return view('admin.akun.edit_admin', compact('akun'));
    }

    public function update(Request $request, $id)
    {
      $akun = User::findOrFail($id);

      $password = $request->get('password');

    //   $data = $request->only('username');

      if ($password == '') {
      } else {
        $data['password'] = bcrypt($request->get('password'));
      }

      $akun->update($data);

    //   Session::flash('info', 'Akun '.$request->get('username').' telah dirubah.');
      return redirect()->route('admin.akun.admin.index');
    }

    public function destroy($id)
    {
        $hapus = User::findOrFail($id);
        // Session::flash('error', 'Akun '.$hapus->username.' telah dihapus.');

        User::find($id)->delete();
        return redirect()->route('admin.akun.admin.index');
    }
}

resources/views/admin/akun/akun_admin.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Akun
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12" align="right">
              <a href="{{ url('/admin/akun/guru') }}" class="btn btn-primary"><span class="fa fa-eye"></span> Akun Karyawan</a>
              <a href="{{ url('/admin/akun/siswa') }}" class="btn btn-success"><span class="fa fa-eye"></span> Akun Siswa</a>
              <br><br>
            </div>
            <div class="col-md-12">

                <div class="box box-primary">

                    <div class="box-header with-border">
                        <h3 class="box-title">Tambah Akun Admin</h3>
                    </div>

                    <div class="box-body">
                      {!! Form::open(['route' => 'admin.akun.admin.store', 'class'=>'form-horizontal'])!!}
                          @include('form._admin_akun_tambah')
                      {!! Form::close() !!}
                    </div>
                </div>
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Akun Admin</h3>
                    </div>

                    <div class="box-body">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <td align="center">No</td>
                                <td align="center">Username</td>
                                <td align="center">Password</td>
                                <td colspan="2" align="center">Aksi</td>
                            </tr>
                            </thead>
                            <tbody>

                            @foreach($akun as $item)
                                <tr>
                                    <td align="center">{{ $no++ }}</td>
                                    <td>{{ $item->username }}</td>
                                    <td align="center">*****</td>
                                    <td align="center">
                                        <a href="{{ route('admin.akun.admin.edit', $item->id) }}" class="btn btn-primary">Ubah</a>
                                    </td>
                                    <td align="center">
                                        {{ Form::open(['route' => ['admin.akun.admin.destroy' , $item->id] ,'method' => 'DELETE']) }}
                                            {{ Form::submit('Hapus', ['class' => 'btn btn-danger js-submit-confirm']) }}
                                        {{ Form::close() }}
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        {{ $akun->appends(compact('page'))->links() }}
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/akun/akun_guru.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Akun
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12" align="right">
              <a href="{{ url('/admin/akun/admin') }}" class="btn btn-primary"><span class="fa fa-eye"></span> Akun Admin</a>
              <a href="{{ url('/admin/akun/siswa') }}" class="btn btn-success"><span class="fa fa-eye"></span> Akun Siswa</a>
              <br><br>
            </div>

            <div class="col-md-12">

                <div class="box box-primary">

                    <div class="box-header with-border">
                        <h3 class="box-title">Akun Karyawan</h3>
                    </div>

                    <div class="box-body">
                        {!! Form::open(['url' => 'admin/akun/guru', 'method'=>'get', 'class'=>'form-inline'])!!}
                          <div class="form-group {!! $errors->has('q') ? 'has-error' : '' !!}">
                              {!! Form::text('q', isset($q) ? $q : null, ['class'=>'form-control', 'placeholder' => 'Cari Akun Karyawan ...']) !!}
                              {!! $errors->first('q', '<p class="help-block">:message</p>') !!}
                          </div>
                        {!! Form::submit('Cari', ['class'=>'btn btn-primary']) !!}
                        {!! Form::close() !!}
                    </div>
                    <div class="box-body">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <td align="center">No</td>
                                <td align="center">Username</td>
                                <td align="center">Password</td>
                                <td align="center">Aksi</td>
                            </tr>
                            </thead>
                            <tbody>

                            @foreach($akun as $item)
                                <tr>
                                    <td align="center">{{ $no++ }}</td>
                                    <td>{{ $item->username }}</td>
                                    <td align="center">*****</td>
                                    <td align="center">
                                        <a href="{{ route('admin.akun.guru.edit', $item->id) }}" class="btn btn-primary">Ubah</a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        {{ $akun->appends(compact('q','page'))->links() }}
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/akun/akun_siswa.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Akun
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12" align="right">
              <a href="{{ url('/admin/akun/admin') }}" class="btn btn-primary"><span class="fa fa-eye"></span> Akun Admin</a>
              <a href="{{ url('/admin/akun/guru') }}" class="btn btn-success"><span class="fa fa-eye"></span> Akun Karyawan</a>
              <br><br>
            </div>
            <div class="col-md-12">

                <div class="box box-primary">

                    <div class="box-header with-border">
                        <h3 class="box-title">Akun Siswa</h3>
                    </div>

                    <div class="box-body">
                        {!! Form::open(['url' => 'admin/akun/siswa', 'method'=>'get', 'class'=>'form-inline'])!!}
                          <div class="form-group {!! $errors->has('q') ? 'has-error' : '' !!}">
                              {!! Form::text('q', isset($q) ? $q : null, ['class'=>'form-control', 'placeholder' => 'Cari Akun Siswa ...']) !!}
                              {!! $errors->first('q', '<p class="help-block">:message</p>') !!}
                          </div>
                        {!! Form::submit('Cari', ['class'=>'btn btn-primary']) !!}
                        {!! Form::close() !!}
                    </div>
                    <div class="box-body">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <td align="center">No</td>
                                <td align="center">Username</td>
                                <td align="center">Password</td>
                                <td align="center">Aksi</td>
                            </tr>
                            </thead>
                            <tbody>

                            @foreach($akun as $item)
                                <tr>
                                    <td align="center">{{ $no++ }}</td>
                                    <td>{{ $item->username }}</td>
                                    <td align="center">*****</td>
                                    <td align="center">
                                        <a href="{{ route('admin.akun.siswa.edit', $item->id) }}" class="btn btn-primary">Ubah</a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        {{ $akun->appends(compact('q','page'))->links() }}
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/akun/edit_admin.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Akun
        </h1>
    </section>

    <section class="content">
        <div class="row">
          <div class="col-md-12" align="right">
            <a href="{{ url('/admin/akun/admin') }}" class="btn btn-primary"><span class="fa fa-eye"></span> Akun Admin</a>
            <br><br>
          </div>
            <div class="col-md-12">

                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">Ubah Akun</h3>
                    </div>
                    <div class="box-body">
                        {!! Form::model($akun, ['route' => ['admin.akun.admin.update', $akun],'method' =>'patch','class'=>'form-horizontal'])!!}
                            @include('form._admin_akun', ['model' => $akun])
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/akun/edit_guru.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Akun
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12" align="right">
              <a href="{{ url('/admin/akun/guru') }}" class="btn btn-primary"><span class="fa fa-eye"></span> Akun Guru</a>
              <br><br>
            </div>
            <div class="col-md-12">

                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">Ubah Akun</h3>
                    </div>
                    <div class="box-body">
                        {!! Form::model($akun, ['route' => ['admin.akun.guru.update', $akun],'method' =>'patch','class'=>'form-horizontal'])!!}
                            @include('form._admin_akun', ['model' => $akun])
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/akun/edit_siswa.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Akun
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12" align="right">
              <a href="{{ url('/admin/akun/siswa') }}" class="btn btn-primary"><span class="fa fa-eye"></span> Akun Siswa</a>
              <br><br>
            </div>
            <div class="col-md-12">

                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">Ubah Akun</h3>
                    </div>
                    <div class="box-body">
                        {!! Form::model($akun, ['route' => ['admin.akun.siswa.update', $akun],'method' =>'patch','class'=>'form-horizontal'])!!}
                            @include('form._admin_akun', ['model' => $akun])
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection